name: Trading Bot Schedule

on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment to run the bot on'
        required: true
        default: trading_bot_demo

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest
    environment: trading_bot_prod
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run trading bot
      run: |
        python trading_bot.py --api_key ${{ secrets.OKX_API_KEY }} --secret_key ${{ secrets.OKX_SECRET_KEY }} --passphrase ${{ secrets.OKX_PASSPHRASE }} --account_type  ${{ vars.OKX_ACCOUNT_TYPE }}